/**
 * Export utilities for Milestone Timeline (Story 8.4).
 *
 * Provides PDF and JPEG export using html2canvas + jsPDF.
 * Captures the DOM element directly for WYSIWYG output.
 */

import html2canvas from 'html2canvas'
import { jsPDF } from 'jspdf'

/**
 * Format current date as YYYY-MM-DD for file names.
 */
function formatFileDate(): string {
  return new Date().toISOString().split('T')[0]
}

/**
 * Prepare a cloned DOM tree for export:
 * - Remove elements marked with data-export-exclude (filter bars, star toggles, Today marker)
 * - Remove text truncation so full milestone statements are visible
 * - Set a minimum width to ensure wide layout
 */
function prepareForExport(clonedEl: HTMLElement): void {
  const doc = clonedEl.ownerDocument

  // Remove elements marked for export exclusion
  doc.querySelectorAll('[data-export-exclude]').forEach(el => el.remove())

  // Remove text truncation classes so full milestone text is visible
  doc.querySelectorAll('.truncate').forEach(el => {
    el.classList.remove('truncate')
    el.classList.add('whitespace-nowrap')
  })
  // Remove max-width constraints that clip milestone text
  doc.querySelectorAll('[class*="max-w-xs"], [class*="max-w-md"]').forEach(el => {
    el.classList.forEach(cls => {
      if (cls.startsWith('max-w-') || cls.includes(':max-w-')) {
        el.classList.remove(cls)
      }
    })
  })

  // Ensure the cloned element is wide enough for full content
  clonedEl.style.minWidth = '1600px'
}

/**
 * Export the milestone timeline element as a PDF file.
 *
 * - A4 portrait with 20mm margins
 * - Header: project name + export date
 * - Footer: page number + "Generated by DecisionLog"
 * - 2x scale for retina quality
 * - Multi-page support for tall timelines
 */
export async function exportAsPDF(element: HTMLElement, projectName: string): Promise<void> {
  const canvas = await html2canvas(element, {
    scale: 2,
    backgroundColor: '#FFFFFF',
    useCORS: true,
    logging: false,
    windowWidth: 1800,
    onclone: (_doc, clonedEl) => prepareForExport(clonedEl),
  })

  const pdf = new jsPDF('p', 'mm', 'a4')
  const pageWidth = pdf.internal.pageSize.getWidth()
  const pageHeight = pdf.internal.pageSize.getHeight()
  const margin = 20
  const imgWidth = pageWidth - margin * 2
  const imgHeight = (canvas.height * imgWidth) / canvas.width

  const headerHeight = 28 // space for header text
  const footerHeight = 15 // space for footer text
  const usableHeight = pageHeight - headerHeight - footerHeight

  // If content fits on one page
  if (imgHeight <= usableHeight) {
    // Header
    pdf.setFontSize(12)
    pdf.text(projectName, margin, 15)
    pdf.setFontSize(8)
    pdf.text(
      `Exported on ${new Date().toLocaleDateString('en-US', {
        year: 'numeric',
        month: 'short',
        day: 'numeric',
      })}`,
      margin,
      20
    )

    // Timeline image
    pdf.addImage(
      canvas.toDataURL('image/jpeg', 0.95),
      'JPEG',
      margin,
      headerHeight,
      imgWidth,
      imgHeight
    )

    // Footer
    pdf.setFontSize(8)
    pdf.text(`Page 1 — Generated by DecisionLog`, margin, pageHeight - 10)
  } else {
    // Multi-page: slice the canvas into page-sized chunks
    const totalPages = Math.ceil(imgHeight / usableHeight)
    const sliceHeight = Math.ceil(canvas.height / totalPages)

    for (let page = 0; page < totalPages; page++) {
      if (page > 0) pdf.addPage()

      // Header
      pdf.setFontSize(12)
      pdf.text(projectName, margin, 15)
      pdf.setFontSize(8)
      pdf.text(
        `Exported on ${new Date().toLocaleDateString('en-US', {
          year: 'numeric',
          month: 'short',
          day: 'numeric',
        })}`,
        margin,
        20
      )

      // Slice canvas for this page
      const sliceCanvas = document.createElement('canvas')
      sliceCanvas.width = canvas.width
      const thisSliceHeight = Math.min(sliceHeight, canvas.height - page * sliceHeight)
      sliceCanvas.height = thisSliceHeight

      const ctx = sliceCanvas.getContext('2d')
      if (ctx) {
        ctx.fillStyle = '#FFFFFF'
        ctx.fillRect(0, 0, sliceCanvas.width, sliceCanvas.height)
        ctx.drawImage(
          canvas,
          0,
          page * sliceHeight,
          canvas.width,
          thisSliceHeight,
          0,
          0,
          canvas.width,
          thisSliceHeight
        )
      }

      const sliceImgHeight = (thisSliceHeight * imgWidth) / canvas.width
      pdf.addImage(
        sliceCanvas.toDataURL('image/jpeg', 0.95),
        'JPEG',
        margin,
        headerHeight,
        imgWidth,
        sliceImgHeight
      )

      // Footer
      pdf.setFontSize(8)
      pdf.text(
        `Page ${page + 1} of ${totalPages} — Generated by DecisionLog`,
        margin,
        pageHeight - 10
      )
    }
  }

  pdf.save(`${projectName}-milestones-${formatFileDate()}.pdf`)
}

/**
 * Export the milestone timeline element as a JPEG image.
 *
 * - 2x scale for retina quality
 * - White background
 * - 90% JPEG compression
 * - Wide rendering to avoid text truncation
 */
export async function exportAsJPEG(element: HTMLElement, projectName: string): Promise<void> {
  const canvas = await html2canvas(element, {
    scale: 2,
    backgroundColor: '#FFFFFF',
    useCORS: true,
    logging: false,
    windowWidth: 1800,
    onclone: (_doc, clonedEl) => prepareForExport(clonedEl),
  })

  const link = document.createElement('a')
  link.download = `${projectName}-milestones-${formatFileDate()}.jpg`
  link.href = canvas.toDataURL('image/jpeg', 0.9)
  link.click()
}
