/**
 * Export utilities for Milestone Timeline (Story 8.4).
 *
 * Provides PDF and JPEG export using html2canvas + jsPDF.
 * Captures the DOM element directly for WYSIWYG output.
 */

import html2canvas from 'html2canvas'
import { jsPDF } from 'jspdf'

/**
 * Format current date as YYYY-MM-DD for file names.
 */
function formatFileDate(): string {
  return new Date().toISOString().split('T')[0]
}

/**
 * Export the milestone timeline element as a PDF file.
 *
 * - A4 portrait with 20mm margins
 * - Header: project name + export date
 * - Footer: page number + "Generated by DecisionLog"
 * - 2x scale for retina quality
 */
export async function exportAsPDF(element: HTMLElement, projectName: string): Promise<void> {
  const canvas = await html2canvas(element, {
    scale: 2,
    backgroundColor: '#FFFFFF',
    useCORS: true,
    logging: false,
  })

  const pdf = new jsPDF('p', 'mm', 'a4')
  const pageWidth = pdf.internal.pageSize.getWidth()
  const pageHeight = pdf.internal.pageSize.getHeight()
  const imgWidth = pageWidth - 40 // 20mm margins on each side
  const imgHeight = (canvas.height * imgWidth) / canvas.width

  // Header
  pdf.setFontSize(12)
  pdf.text(projectName, 20, 15)
  pdf.setFontSize(8)
  pdf.text(
    `Exported on ${new Date().toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'short',
      day: 'numeric',
    })}`,
    20,
    20
  )

  // Timeline image
  pdf.addImage(
    canvas.toDataURL('image/jpeg', 0.95),
    'JPEG',
    20,
    25,
    imgWidth,
    imgHeight
  )

  // Footer
  pdf.setFontSize(8)
  pdf.text(
    `Page 1 — Generated by DecisionLog`,
    20,
    pageHeight - 10
  )

  pdf.save(`${projectName}-milestones-${formatFileDate()}.pdf`)
}

/**
 * Export the milestone timeline element as a JPEG image.
 *
 * - 2x scale for retina quality
 * - White background
 * - 90% JPEG compression
 */
export async function exportAsJPEG(element: HTMLElement, projectName: string): Promise<void> {
  const canvas = await html2canvas(element, {
    scale: 2,
    backgroundColor: '#FFFFFF',
    useCORS: true,
    logging: false,
  })

  const link = document.createElement('a')
  link.download = `${projectName}-milestones-${formatFileDate()}.jpg`
  link.href = canvas.toDataURL('image/jpeg', 0.9)
  link.click()
}
